
<Player>:
    # size: 20, 20
    canvas:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            size: self.size
            pos: self.pos


<Cloud>:
    canvas:
        Color:
            rgba: 1,0,0,1
        Rectangle:
            size: self.size
            pos: self.pos

<Cloud2>:
    x: 50
    canvas:
        Color:
            rgba: 0,1,0,1
        Rectangle:
            size: self.size
            pos: self.pos


<Game>: